### ISSUE TITLE
No background

### ISSUE THREAD

**Issue by ColetteYoude** [alexward1981/portfolio#13]
Nokia Lumia - No background on either landscape or portrait. The background only shows sky and green - no London artwork. Badly aligned Alex mini me.

See pics
https://mail.google.com/mail/u/0/?ui=2&ik=2540eca9d4&view=att&th=14b4699ca6bc46a6&attid=0.1&disp=safe&zw, took a pic of portrait and landscape. See pictures.

https://mail.google.com/mail/u/0/?ui=2&ik=2540eca9d4&view=att&th=14b46884bea53d72&attid=0.1&disp=safe&zw

Samsung galaxy android browser HAS background in landscape but not portrait.

**Comment by foxleigh81** [comment]
Fixed as part of ticket #10
