### ISSUE TITLE
Overlap

### ISSUE THREAD

**Issue by ColetteYoude** [alexward1981/portfolio#15]
Scrolly text and download button at top of webpage overlap. Samsung Galaxy S5 chrome browser portrait.

https://mail.google.com/mail/u/0/?ui=2&ik=2540eca9d4&view=att&th=14b46b418e4543b6&attid=0.1&disp=safe&zw

**Comment by foxleigh81** [comment]
Fixed in 49683a3c23710436c5bc80092966afe7ac130616
